title: Aoiryu
url: https://aoi.ryu.dev.br/
# https://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: "/blog/page_:num/"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate