title: Aoiryu
url: https://aoi.ryu.dev.br/

words_per_minutes: 200
# https://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: "/blog/page_:num/"

theme_color: "#A6C1FF"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
